### ISSUE TITLE
Humble Bundle

### ISSUE THREAD

**Issue by Innomen** [ssokolow/lgogd_uri#20]
From a non-coder user perspective github is wildly complicated when it comes to figuring out how to determine the status of things and knowing where to say what and what has already been said with regard to communicating with the dev.

So pardon if this is in the wrong place or if it's already covered or obviated somewhere else.

FWIW, humble library export still isn't working. I say still because there was a link to a fork or something that worked with humble but that seems to just take me back to the main thing.

My ultimate goal is to build a list of all my unredeemed and drm free games in http://www.completionator.com.

Anyway, thanks for what you do, I look forward to being able to use it someday :)

**Comment by ssokolow** [comment]
You posted this on `lgogd_uri` when, judging by your content, you meant to post it on `itad_importer`.

That aside, no problem. I'm happy to help.

Here's where you have to be looking to see the difference between the normal download and the humble-fix branch.

## ![master branch](https://cloud.githubusercontent.com/assets/46915/8142963/2a517fe6-1162-11e5-9dfe-49f23bc4dfcb.png)

![humble-fix branch](https://cloud.githubusercontent.com/assets/46915/8142966/2f40b364-1162-11e5-9340-dbf88cecb463.png)

The link in the README file explicitly points to the `master` branch because of limitations in linking to non-prettyprinted file contents, so you need to install it by doing this...

![step 1](https://cloud.githubusercontent.com/assets/46915/8142982/6a19b8d6-1163-11e5-9ece-03ecfeadec89.png)
![step 2](https://cloud.githubusercontent.com/assets/46915/8142987/7c153448-1163-11e5-9f2c-ce648b32c192.png)

This diagram should help to explain the whole thing:
![network diagram](https://cloud.githubusercontent.com/assets/46915/8143007/0df19280-1164-11e5-9138-26a1c4c83712.png)

**Comment by ssokolow** [comment]
Just be aware that `humble-fix` hasn't been merged into `master` yet because it currently doesn't know the difference between DRM-free games and Steam keys, so it'll import your Humble steam keys as "owned on Humble" unless you manually uncheck them.

**Comment by Innomen** [comment]
First of all thanks very much for the handholding. It worked excellently. You went above and beyond and I appreciate it :)

Secondly, I had to create a collection first hehe, otherwise I got a 404, but once that was done it totally worked :)

I'll recreate the collection later if you add features, make changes, etc. 

I hope you'll add bundle stars and indiegala eventually :) 

I did humble and indiegamestand. Gog didn't have the button anywhere. I think they changed things because your screenshots look different.

Anyway thanks very much :)

P.S. I have no idea how I managed to post on a completely different project. Git so hates me. I wish you could move it like in a forum hehe.

**Comment by ssokolow** [comment]
Glad I could help.

GOG being broken is ssokolow/itad_importer#11 and it's because GOG recently did a major rewrite of their account system and I couldn't quickly fix the script because:
1. I have exams coming up
2. I didn't take pagination into account when I wrote the script, so I need to completely redesign its innards.

However, if I can make time to figure out a minor kink (inserted button ignores clicks), I can at least get "Import current page" working soon.

As for the others, keep in mind that this is a script for importing based on where you go to download, not where you went to buy:
- I've yet to see a Bundle Stars deal that offered anything other than Steam keys (which you handle via ITAD's own Steam sync)
- I can't remember whether any of my IndieGala bundles have direct-download (non-Steam, non-Desura) games but, if they do, I'll get around to it.

**Comment by ssokolow** [comment]
Oh, and no need to re-create anything. If you can't just click "Export to ITAD" to apply updates to an existing ITAD collection, then it's a bug, either in my script or in the ITAD API it talks to.

**Comment by Innomen** [comment]
Ahh cool cool. Just so you know, like for user case study purposes or whatever hehe:

One of the reasons to inventory my games is knowing which ones I have bound to my steam and account and which ones are still in key/giftable format. I tend to leave games unredeemed as long as I can because binding them to my steam account closes options.

As of now that's mostly easy to do with a little deduction and some manual list editing. (Collection + Bundle Stars/Gala - Steam Games == unredeemed games for trade/gifting) 

Super Super helpful even as is. Good luck with exams. :) I suspect you'll trounce them.

**Comment by ssokolow** [comment]
Regarding un-redeemed keys, I just keep a list of "my collection" page links in the form of 80x15 badges. Here's what it looked like back in 2012.

<a href="http://www.desura.com/members/ssokolow/images/updated-example-of-how-i-manage-my-games" title="Updated example of how I manage my games - Desura" target="_blank"><img src="http://d2oah9q9xdinv5.cloudfront.net/cache/images/members/1/782/781961/thumb_620x2000/managed.png" alt="Updated example of how I manage my games" width="533" /></a>

Plus, personally, I consider Steam keys to be not owning at all, because when it comes down to it, ignoring what the law says, you have more ownership of a pirated copy than you do of a game with online DRM.

(And I take pride in legally owning everything I play. ...well... aside from Portal. In a moment of weakness, I borrowed my brother's PC and Steam account to reconcile my desire to play it with my principles and my refusal to install Steam or financially endorse Valve's decision to make Portal Steam-only.)

**Comment by Innomen** [comment]
Very tidy :)
